// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// // import ConvexClientProvider from "./dashboard/ConvexClientProvider";
// import ConvexClientProvider from "./ConvexClientProvider";
// import { Header } from "./header";
// // import Header from "@/_components/Header";
// import { Toaster } from "@/components/ui/toaster";
// import { Footer } from "./footer";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <ConvexClientProvider>
//         <Toaster />
//         <Header />
//         {children}
//         <Footer />
//         </ConvexClientProvider>
//       </body>
//     </html>
//   );
// }



"use client";

import Footer from "@/_components/Footer";
import Header from "@/_components/Header";
import ScrollToTop from "@/_components/ScrollToTop";
// import "node_modules/react-modal-video/css/modal-video.css";
import "../styles/index.css";
import { Providers } from "./provider";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="dark:bg-black">
        <Providers>
          {/* <Header /> */}
          {children}
          {/* <Footer /> */}
          <ScrollToTop />
        </Providers>
      </body>
    </html>
  );
}
